name: 'Raku Container Action with compiler'
description: 'Container action using Raku'
author: 'Fritz Zaucker'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-pull-request'
  color: 'purple'
